"""Add AliasDictionary and ReviewAuditLog

Revision ID: 71b6005b08a0
Revises: a4bae443ecee
Create Date: 2026-05-23 23:57:53.068628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71b6005b08a0'
down_revision: Union[str, None] = 'a4bae443ecee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alias_dictionaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alias_id', sa.String(length=255), nullable=False),
    sa.Column('alias_type', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('resolution', sa.String(length=255), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alias_dictionaries_alias_id'), 'alias_dictionaries', ['alias_id'], unique=True)
    op.create_index(op.f('ix_alias_dictionaries_alias_type'), 'alias_dictionaries', ['alias_type'], unique=False)
    op.create_index(op.f('ix_alias_dictionaries_enabled'), 'alias_dictionaries', ['enabled'], unique=False)
    op.create_index(op.f('ix_alias_dictionaries_source_platform'), 'alias_dictionaries', ['source_platform'], unique=False)
    op.create_index(op.f('ix_alias_dictionaries_token'), 'alias_dictionaries', ['token'], unique=False)
    op.create_table('review_audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decision_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=True),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('target_alias', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_audit_logs_action'), 'review_audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_review_audit_logs_candidate_id'), 'review_audit_logs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_review_audit_logs_decision_id'), 'review_audit_logs', ['decision_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_audit_logs_decision_id'), table_name='review_audit_logs')
    op.drop_index(op.f('ix_review_audit_logs_candidate_id'), table_name='review_audit_logs')
    op.drop_index(op.f('ix_review_audit_logs_action'), table_name='review_audit_logs')
    op.drop_table('review_audit_logs')
    op.drop_index(op.f('ix_alias_dictionaries_token'), table_name='alias_dictionaries')
    op.drop_index(op.f('ix_alias_dictionaries_source_platform'), table_name='alias_dictionaries')
    op.drop_index(op.f('ix_alias_dictionaries_enabled'), table_name='alias_dictionaries')
    op.drop_index(op.f('ix_alias_dictionaries_alias_type'), table_name='alias_dictionaries')
    op.drop_index(op.f('ix_alias_dictionaries_alias_id'), table_name='alias_dictionaries')
    op.drop_table('alias_dictionaries')
    # ### end Alembic commands ###
