"""Add escalation layer tables

Revision ID: 949425d72795
Revises: c186701f961f
Create Date: 2026-05-17 15:59:23.824815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '949425d72795'
down_revision: Union[str, None] = 'c186701f961f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('environment_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('environment_name', sa.String(length=255), nullable=False),
    sa.Column('environment_type', sa.String(length=50), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('ebay_api_base_url', sa.String(length=255), nullable=False),
    sa.Column('ebay_oauth_base_url', sa.String(length=255), nullable=False),
    sa.Column('application_keyset_ref', sa.String(length=255), nullable=True),
    sa.Column('supports_live_publish', sa.Boolean(), nullable=False),
    sa.Column('supports_test_users', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environment_profiles_environment_id'), 'environment_profiles', ['environment_id'], unique=True)
    op.create_index(op.f('ix_environment_profiles_environment_type'), 'environment_profiles', ['environment_type'], unique=False)
    op.create_table('escalation_policies',
    sa.Column('policy_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('seller_account_id', sa.String(length=255), nullable=True),
    sa.Column('environment_type', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('base_severity', sa.String(length=50), nullable=False),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('reminder_interval_seconds', sa.Integer(), nullable=False),
    sa.Column('reminder_max_count', sa.Integer(), nullable=True),
    sa.Column('allow_reminder_after_ack', sa.Boolean(), nullable=False),
    sa.Column('silence_respected', sa.Boolean(), nullable=False),
    sa.Column('auto_resolve_on_source_recovery', sa.Boolean(), nullable=False),
    sa.Column('escalation_enabled', sa.Boolean(), nullable=False),
    sa.Column('escalation_steps_json', sa.JSON(), nullable=False),
    sa.Column('dedupe_scope', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('policy_id')
    )
    op.create_index(op.f('ix_escalation_policies_event_type'), 'escalation_policies', ['event_type'], unique=False)
    op.create_index(op.f('ix_escalation_policies_name'), 'escalation_policies', ['name'], unique=True)
    op.create_table('escalation_state_transitions',
    sa.Column('transition_id', sa.String(length=255), nullable=False),
    sa.Column('state_id', sa.String(length=255), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('previous_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('note', sa.String(length=1000), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('transition_id')
    )
    op.create_index(op.f('ix_escalation_state_transitions_state_id'), 'escalation_state_transitions', ['state_id'], unique=False)
    op.create_table('escalation_states',
    sa.Column('state_id', sa.String(length=255), nullable=False),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('source_history_id', sa.String(length=255), nullable=True),
    sa.Column('source_event_type', sa.String(length=100), nullable=False),
    sa.Column('seller_account_id', sa.String(length=255), nullable=True),
    sa.Column('environment_type', sa.String(length=50), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('dedupe_key', sa.String(length=500), nullable=False),
    sa.Column('current_status', sa.String(length=50), nullable=False),
    sa.Column('current_severity', sa.String(length=50), nullable=False),
    sa.Column('current_priority', sa.String(length=50), nullable=False),
    sa.Column('reminder_count', sa.Integer(), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_notified_at', sa.DateTime(), nullable=True),
    sa.Column('last_reminded_at', sa.DateTime(), nullable=True),
    sa.Column('last_escalated_at', sa.DateTime(), nullable=True),
    sa.Column('acked_at', sa.DateTime(), nullable=True),
    sa.Column('acked_by', sa.String(length=255), nullable=True),
    sa.Column('silenced_until', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_by', sa.String(length=255), nullable=True),
    sa.Column('resolution_note', sa.String(length=1000), nullable=True),
    sa.Column('source_status_snapshot', sa.JSON(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('state_id')
    )
    op.create_index(op.f('ix_escalation_states_current_status'), 'escalation_states', ['current_status'], unique=False)
    op.create_index(op.f('ix_escalation_states_dedupe_key'), 'escalation_states', ['dedupe_key'], unique=True)
    op.create_index(op.f('ix_escalation_states_environment_type'), 'escalation_states', ['environment_type'], unique=False)
    op.create_index(op.f('ix_escalation_states_last_notified_at'), 'escalation_states', ['last_notified_at'], unique=False)
    op.create_index(op.f('ix_escalation_states_resolved_at'), 'escalation_states', ['resolved_at'], unique=False)
    op.create_index(op.f('ix_escalation_states_seller_account_id'), 'escalation_states', ['seller_account_id'], unique=False)
    op.create_index(op.f('ix_escalation_states_silenced_until'), 'escalation_states', ['silenced_until'], unique=False)
    op.create_index(op.f('ix_escalation_states_sku'), 'escalation_states', ['sku'], unique=False)
    op.create_index(op.f('ix_escalation_states_source_event_id'), 'escalation_states', ['source_event_id'], unique=False)
    op.create_index(op.f('ix_escalation_states_source_event_type'), 'escalation_states', ['source_event_type'], unique=False)
    op.create_table('notification_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('source_layer', sa.String(length=100), nullable=True),
    sa.Column('source_run_id', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('seller_account_id', sa.String(length=255), nullable=True),
    sa.Column('environment_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('channel_name', sa.String(length=50), nullable=False),
    sa.Column('dispatch_status', sa.String(length=20), nullable=False),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('meta_json', sa.JSON(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=255), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_histories_channel_name'), 'notification_histories', ['channel_name'], unique=False)
    op.create_index(op.f('ix_notification_histories_created_at'), 'notification_histories', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_histories_environment_type'), 'notification_histories', ['environment_type'], unique=False)
    op.create_index(op.f('ix_notification_histories_event_id'), 'notification_histories', ['event_id'], unique=False)
    op.create_index(op.f('ix_notification_histories_event_type'), 'notification_histories', ['event_type'], unique=False)
    op.create_index(op.f('ix_notification_histories_seller_account_id'), 'notification_histories', ['seller_account_id'], unique=False)
    op.create_index(op.f('ix_notification_histories_sku'), 'notification_histories', ['sku'], unique=False)
    op.create_index(op.f('ix_notification_histories_source_run_id'), 'notification_histories', ['source_run_id'], unique=False)
    op.create_table('seller_location_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('seller_account_id', sa.String(length=255), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('merchant_location_key', sa.String(length=255), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_location_snapshots_environment_id'), 'seller_location_snapshots', ['environment_id'], unique=False)
    op.create_index(op.f('ix_seller_location_snapshots_fetched_at'), 'seller_location_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_seller_location_snapshots_merchant_location_key'), 'seller_location_snapshots', ['merchant_location_key'], unique=False)
    op.create_index(op.f('ix_seller_location_snapshots_seller_account_id'), 'seller_location_snapshots', ['seller_account_id'], unique=False)
    op.create_index(op.f('ix_seller_location_snapshots_snapshot_id'), 'seller_location_snapshots', ['snapshot_id'], unique=True)
    op.create_table('seller_policy_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_id', sa.String(length=255), nullable=False),
    sa.Column('seller_account_id', sa.String(length=255), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('marketplace_id', sa.String(length=50), nullable=False),
    sa.Column('fulfillment_policy_id', sa.String(length=255), nullable=True),
    sa.Column('payment_policy_id', sa.String(length=255), nullable=True),
    sa.Column('return_policy_id', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_policy_snapshots_environment_id'), 'seller_policy_snapshots', ['environment_id'], unique=False)
    op.create_index(op.f('ix_seller_policy_snapshots_fetched_at'), 'seller_policy_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_seller_policy_snapshots_marketplace_id'), 'seller_policy_snapshots', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_seller_policy_snapshots_seller_account_id'), 'seller_policy_snapshots', ['seller_account_id'], unique=False)
    op.create_index(op.f('ix_seller_policy_snapshots_snapshot_id'), 'seller_policy_snapshots', ['snapshot_id'], unique=True)
    op.create_table('seller_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_account_id', sa.String(length=255), nullable=False),
    sa.Column('seller_name', sa.String(length=255), nullable=False),
    sa.Column('seller_label', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('environment_mode', sa.String(length=50), nullable=False),
    sa.Column('default_marketplace_id', sa.String(length=50), nullable=False),
    sa.Column('default_currency', sa.String(length=10), nullable=False),
    sa.Column('default_merchant_location_key', sa.String(length=255), nullable=True),
    sa.Column('default_fulfillment_policy_id', sa.String(length=255), nullable=True),
    sa.Column('default_payment_policy_id', sa.String(length=255), nullable=True),
    sa.Column('default_return_policy_id', sa.String(length=255), nullable=True),
    sa.Column('auth_profile_ref', sa.String(length=255), nullable=True),
    sa.Column('notification_profile_ref', sa.String(length=255), nullable=True),
    sa.Column('scheduling_profile_ref', sa.String(length=255), nullable=True),
    sa.Column('tags_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seller_profiles_enabled'), 'seller_profiles', ['enabled'], unique=False)
    op.create_index(op.f('ix_seller_profiles_seller_account_id'), 'seller_profiles', ['seller_account_id'], unique=True)
    op.create_table('seller_environment_bindings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('binding_id', sa.String(length=255), nullable=False),
    sa.Column('seller_account_id', sa.String(length=255), nullable=False),
    sa.Column('environment_id', sa.String(length=50), nullable=False),
    sa.Column('active_flag', sa.Boolean(), nullable=False),
    sa.Column('marketplace_id', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('merchant_location_key', sa.String(length=255), nullable=True),
    sa.Column('fulfillment_policy_id', sa.String(length=255), nullable=True),
    sa.Column('payment_policy_id', sa.String(length=255), nullable=True),
    sa.Column('return_policy_id', sa.String(length=255), nullable=True),
    sa.Column('refresh_token_ref', sa.String(length=255), nullable=True),
    sa.Column('auth_scope_profile', sa.String(length=255), nullable=True),
    sa.Column('notification_channel_profile', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['environment_id'], ['environment_profiles.environment_id'], ),
    sa.ForeignKeyConstraint(['seller_account_id'], ['seller_profiles.seller_account_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_seller_env_unique', 'seller_environment_bindings', ['seller_account_id', 'environment_id'], unique=True)
    op.create_index(op.f('ix_seller_environment_bindings_active_flag'), 'seller_environment_bindings', ['active_flag'], unique=False)
    op.create_index(op.f('ix_seller_environment_bindings_binding_id'), 'seller_environment_bindings', ['binding_id'], unique=True)
    op.create_index(op.f('ix_seller_environment_bindings_environment_id'), 'seller_environment_bindings', ['environment_id'], unique=False)
    op.create_index(op.f('ix_seller_environment_bindings_seller_account_id'), 'seller_environment_bindings', ['seller_account_id'], unique=False)
    op.add_column('candidate_evidences', sa.Column('seller_account_id', sa.String(length=255), nullable=True))
    op.add_column('candidate_evidences', sa.Column('environment_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_candidate_evidences_environment_type'), 'candidate_evidences', ['environment_type'], unique=False)
    op.create_index(op.f('ix_candidate_evidences_seller_account_id'), 'candidate_evidences', ['seller_account_id'], unique=False)
    op.add_column('ebay_listings', sa.Column('seller_account_id', sa.String(length=255), nullable=True))
    op.add_column('ebay_listings', sa.Column('environment_type', sa.String(length=50), nullable=True))
    op.add_column('ebay_listings', sa.Column('listing_status', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_ebay_listings_environment_type'), 'ebay_listings', ['environment_type'], unique=False)
    op.create_index(op.f('ix_ebay_listings_seller_account_id'), 'ebay_listings', ['seller_account_id'], unique=False)
    op.add_column('job_runs', sa.Column('seller_account_id', sa.String(length=255), nullable=True))
    op.add_column('job_runs', sa.Column('environment_type', sa.String(length=50), nullable=True))
    op.add_column('job_runs', sa.Column('marketplace_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_job_runs_environment_type'), 'job_runs', ['environment_type'], unique=False)
    op.create_index(op.f('ix_job_runs_seller_account_id'), 'job_runs', ['seller_account_id'], unique=False)
    op.add_column('monitoring_events', sa.Column('seller_account_id', sa.String(length=255), nullable=True))
    op.add_column('monitoring_events', sa.Column('environment_type', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_monitoring_events_environment_type'), 'monitoring_events', ['environment_type'], unique=False)
    op.create_index(op.f('ix_monitoring_events_seller_account_id'), 'monitoring_events', ['seller_account_id'], unique=False)
    op.add_column('product_candidates', sa.Column('seller_account_id', sa.String(length=255), nullable=True))
    op.add_column('product_candidates', sa.Column('environment_type', sa.String(length=50), nullable=True))
    op.add_column('product_candidates', sa.Column('marketplace_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_product_candidates_environment_type'), 'product_candidates', ['environment_type'], unique=False)
    op.create_index(op.f('ix_product_candidates_marketplace_id'), 'product_candidates', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_product_candidates_seller_account_id'), 'product_candidates', ['seller_account_id'], unique=False)
    op.drop_index(op.f('ix_source_items_source_item_id'), table_name='source_items')
    op.create_index(op.f('ix_source_items_source_item_id'), 'source_items', ['source_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_source_items_source_item_id'), table_name='source_items')
    op.create_index(op.f('ix_source_items_source_item_id'), 'source_items', ['source_item_id'], unique=False)
    op.drop_index(op.f('ix_product_candidates_seller_account_id'), table_name='product_candidates')
    op.drop_index(op.f('ix_product_candidates_marketplace_id'), table_name='product_candidates')
    op.drop_index(op.f('ix_product_candidates_environment_type'), table_name='product_candidates')
    op.drop_column('product_candidates', 'marketplace_id')
    op.drop_column('product_candidates', 'environment_type')
    op.drop_column('product_candidates', 'seller_account_id')
    op.drop_index(op.f('ix_monitoring_events_seller_account_id'), table_name='monitoring_events')
    op.drop_index(op.f('ix_monitoring_events_environment_type'), table_name='monitoring_events')
    op.drop_column('monitoring_events', 'environment_type')
    op.drop_column('monitoring_events', 'seller_account_id')
    op.drop_index(op.f('ix_job_runs_seller_account_id'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_environment_type'), table_name='job_runs')
    op.drop_column('job_runs', 'marketplace_id')
    op.drop_column('job_runs', 'environment_type')
    op.drop_column('job_runs', 'seller_account_id')
    op.drop_index(op.f('ix_ebay_listings_seller_account_id'), table_name='ebay_listings')
    op.drop_index(op.f('ix_ebay_listings_environment_type'), table_name='ebay_listings')
    op.drop_column('ebay_listings', 'listing_status')
    op.drop_column('ebay_listings', 'environment_type')
    op.drop_column('ebay_listings', 'seller_account_id')
    op.drop_index(op.f('ix_candidate_evidences_seller_account_id'), table_name='candidate_evidences')
    op.drop_index(op.f('ix_candidate_evidences_environment_type'), table_name='candidate_evidences')
    op.drop_column('candidate_evidences', 'environment_type')
    op.drop_column('candidate_evidences', 'seller_account_id')
    op.drop_index(op.f('ix_seller_environment_bindings_seller_account_id'), table_name='seller_environment_bindings')
    op.drop_index(op.f('ix_seller_environment_bindings_environment_id'), table_name='seller_environment_bindings')
    op.drop_index(op.f('ix_seller_environment_bindings_binding_id'), table_name='seller_environment_bindings')
    op.drop_index(op.f('ix_seller_environment_bindings_active_flag'), table_name='seller_environment_bindings')
    op.drop_index('idx_seller_env_unique', table_name='seller_environment_bindings')
    op.drop_table('seller_environment_bindings')
    op.drop_index(op.f('ix_seller_profiles_seller_account_id'), table_name='seller_profiles')
    op.drop_index(op.f('ix_seller_profiles_enabled'), table_name='seller_profiles')
    op.drop_table('seller_profiles')
    op.drop_index(op.f('ix_seller_policy_snapshots_snapshot_id'), table_name='seller_policy_snapshots')
    op.drop_index(op.f('ix_seller_policy_snapshots_seller_account_id'), table_name='seller_policy_snapshots')
    op.drop_index(op.f('ix_seller_policy_snapshots_marketplace_id'), table_name='seller_policy_snapshots')
    op.drop_index(op.f('ix_seller_policy_snapshots_fetched_at'), table_name='seller_policy_snapshots')
    op.drop_index(op.f('ix_seller_policy_snapshots_environment_id'), table_name='seller_policy_snapshots')
    op.drop_table('seller_policy_snapshots')
    op.drop_index(op.f('ix_seller_location_snapshots_snapshot_id'), table_name='seller_location_snapshots')
    op.drop_index(op.f('ix_seller_location_snapshots_seller_account_id'), table_name='seller_location_snapshots')
    op.drop_index(op.f('ix_seller_location_snapshots_merchant_location_key'), table_name='seller_location_snapshots')
    op.drop_index(op.f('ix_seller_location_snapshots_fetched_at'), table_name='seller_location_snapshots')
    op.drop_index(op.f('ix_seller_location_snapshots_environment_id'), table_name='seller_location_snapshots')
    op.drop_table('seller_location_snapshots')
    op.drop_index(op.f('ix_notification_histories_source_run_id'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_sku'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_seller_account_id'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_event_type'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_event_id'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_environment_type'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_created_at'), table_name='notification_histories')
    op.drop_index(op.f('ix_notification_histories_channel_name'), table_name='notification_histories')
    op.drop_table('notification_histories')
    op.drop_index(op.f('ix_escalation_states_source_event_type'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_source_event_id'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_sku'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_silenced_until'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_seller_account_id'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_resolved_at'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_last_notified_at'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_environment_type'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_dedupe_key'), table_name='escalation_states')
    op.drop_index(op.f('ix_escalation_states_current_status'), table_name='escalation_states')
    op.drop_table('escalation_states')
    op.drop_index(op.f('ix_escalation_state_transitions_state_id'), table_name='escalation_state_transitions')
    op.drop_table('escalation_state_transitions')
    op.drop_index(op.f('ix_escalation_policies_name'), table_name='escalation_policies')
    op.drop_index(op.f('ix_escalation_policies_event_type'), table_name='escalation_policies')
    op.drop_table('escalation_policies')
    op.drop_index(op.f('ix_environment_profiles_environment_type'), table_name='environment_profiles')
    op.drop_index(op.f('ix_environment_profiles_environment_id'), table_name='environment_profiles')
    op.drop_table('environment_profiles')
    # ### end Alembic commands ###
