"""Add listing handoff tables

Revision ID: 96ebe660ac9d
Revises: ea36a232da27
Create Date: 2026-05-24 16:19:50.826754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96ebe660ac9d'
down_revision: Union[str, None] = 'ea36a232da27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_handoffs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handoff_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('ranking_decision_id', sa.String(length=255), nullable=True),
    sa.Column('seller_account_id', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('handoff_status', sa.String(length=50), nullable=False),
    sa.Column('handoff_decision', sa.String(length=50), nullable=False),
    sa.Column('execution_allowed', sa.Boolean(), nullable=False),
    sa.Column('dispatch_target', sa.String(length=50), nullable=False),
    sa.Column('batch_id', sa.String(length=255), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('duplicate_suppressed', sa.Boolean(), nullable=False),
    sa.Column('deferred', sa.Boolean(), nullable=False),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('block_reasons_json', sa.JSON(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('explanation_lines_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['canonical_product_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_handoffs_batch_id'), 'listing_handoffs', ['batch_id'], unique=False)
    op.create_index(op.f('ix_listing_handoffs_candidate_id'), 'listing_handoffs', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_listing_handoffs_handoff_decision'), 'listing_handoffs', ['handoff_decision'], unique=False)
    op.create_index(op.f('ix_listing_handoffs_handoff_id'), 'listing_handoffs', ['handoff_id'], unique=True)
    op.create_index(op.f('ix_listing_handoffs_handoff_status'), 'listing_handoffs', ['handoff_status'], unique=False)
    op.create_index(op.f('ix_listing_handoffs_idempotency_key'), 'listing_handoffs', ['idempotency_key'], unique=False)
    op.create_index(op.f('ix_listing_handoffs_next_retry_at'), 'listing_handoffs', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_listing_handoffs_ranking_decision_id'), 'listing_handoffs', ['ranking_decision_id'], unique=False)
    op.create_index(op.f('ix_listing_handoffs_seller_account_id'), 'listing_handoffs', ['seller_account_id'], unique=False)
    op.create_table('listing_handoff_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.String(length=255), nullable=False),
    sa.Column('handoff_id', sa.String(length=255), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempt_status', sa.String(length=50), nullable=False),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['handoff_id'], ['listing_handoffs.handoff_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_handoff_attempts_attempt_id'), 'listing_handoff_attempts', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_listing_handoff_attempts_attempt_status'), 'listing_handoff_attempts', ['attempt_status'], unique=False)
    op.create_index(op.f('ix_listing_handoff_attempts_handoff_id'), 'listing_handoff_attempts', ['handoff_id'], unique=False)
    op.create_table('listing_handoff_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handoff_id', sa.String(length=255), nullable=False),
    sa.Column('from_status', sa.String(length=50), nullable=False),
    sa.Column('to_status', sa.String(length=50), nullable=False),
    sa.Column('transition_reason', sa.Text(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('occurred_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['handoff_id'], ['listing_handoffs.handoff_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_handoff_transitions_handoff_id'), 'listing_handoff_transitions', ['handoff_id'], unique=False)
    op.create_index(op.f('ix_listing_handoff_transitions_occurred_at'), 'listing_handoff_transitions', ['occurred_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_handoff_transitions_occurred_at'), table_name='listing_handoff_transitions')
    op.drop_index(op.f('ix_listing_handoff_transitions_handoff_id'), table_name='listing_handoff_transitions')
    op.drop_table('listing_handoff_transitions')
    op.drop_index(op.f('ix_listing_handoff_attempts_handoff_id'), table_name='listing_handoff_attempts')
    op.drop_index(op.f('ix_listing_handoff_attempts_attempt_status'), table_name='listing_handoff_attempts')
    op.drop_index(op.f('ix_listing_handoff_attempts_attempt_id'), table_name='listing_handoff_attempts')
    op.drop_table('listing_handoff_attempts')
    op.drop_index(op.f('ix_listing_handoffs_seller_account_id'), table_name='listing_handoffs')
    op.drop_index(op.f('ix_listing_handoffs_ranking_decision_id'), table_name='listing_handoffs')
    op.drop_index(op.f('ix_listing_handoffs_next_retry_at'), table_name='listing_handoffs')
    op.drop_index(op.f('ix_listing_handoffs_idempotency_key'), table_name='listing_handoffs')
    op.drop_index(op.f('ix_listing_handoffs_handoff_status'), table_name='listing_handoffs')
    op.drop_index(op.f('ix_listing_handoffs_handoff_id'), table_name='listing_handoffs')
    op.drop_index(op.f('ix_listing_handoffs_handoff_decision'), table_name='listing_handoffs')
    op.drop_index(op.f('ix_listing_handoffs_candidate_id'), table_name='listing_handoffs')
    op.drop_index(op.f('ix_listing_handoffs_batch_id'), table_name='listing_handoffs')
    op.drop_table('listing_handoffs')
    # ### end Alembic commands ###
