"""Add escalation v0.2 extensions

Revision ID: a08ea3afd1a9
Revises: 949425d72795
Create Date: 2026-05-17 17:31:46.863002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08ea3afd1a9'
down_revision: Union[str, None] = '949425d72795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escalation_notes',
    sa.Column('note_id', sa.String(length=255), nullable=False),
    sa.Column('state_id', sa.String(length=255), nullable=False),
    sa.Column('author_id', sa.String(length=255), nullable=False),
    sa.Column('author_type', sa.String(length=50), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('note_id')
    )
    op.create_index('idx_esc_note_state_created', 'escalation_notes', ['state_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_escalation_notes_state_id'), 'escalation_notes', ['state_id'], unique=False)
    op.create_table('maintenance_windows',
    sa.Column('window_id', sa.String(length=255), nullable=False),
    sa.Column('seller_account_id', sa.String(length=255), nullable=True),
    sa.Column('environment_type', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('window_id')
    )
    op.create_index('idx_maint_enabled_times', 'maintenance_windows', ['enabled', 'starts_at', 'ends_at'], unique=False)
    op.create_index('idx_maint_scope', 'maintenance_windows', ['seller_account_id', 'environment_type', 'event_type'], unique=False)
    op.add_column('escalation_policies', sa.Column('policy_version', sa.Integer(), nullable=False))
    op.add_column('escalation_policies', sa.Column('re_escalation_enabled', sa.Boolean(), nullable=False))
    op.add_column('escalation_policies', sa.Column('re_escalation_interval_seconds', sa.Integer(), nullable=True))
    op.add_column('escalation_policies', sa.Column('re_escalation_max_count', sa.Integer(), nullable=True))
    op.add_column('escalation_policies', sa.Column('sla_target_seconds', sa.Integer(), nullable=True))
    op.add_column('escalation_policies', sa.Column('sla_breach_severity', sa.String(length=50), nullable=True))
    op.add_column('escalation_policies', sa.Column('sla_breach_priority', sa.String(length=50), nullable=True))
    op.add_column('escalation_policies', sa.Column('maintenance_window_respected', sa.Boolean(), nullable=False))
    op.add_column('escalation_policies', sa.Column('bulk_action_enabled', sa.Boolean(), nullable=False))
    op.add_column('escalation_policies', sa.Column('route_override_key', sa.String(length=100), nullable=True))
    op.create_index('idx_esc_policy_version_enabled', 'escalation_policies', ['policy_version', 'enabled'], unique=False)
    op.add_column('escalation_states', sa.Column('aging_seconds', sa.Integer(), nullable=True))
    op.add_column('escalation_states', sa.Column('aging_bucket', sa.String(length=50), nullable=True))
    op.add_column('escalation_states', sa.Column('sla_target_seconds', sa.Integer(), nullable=True))
    op.add_column('escalation_states', sa.Column('sla_breached_at', sa.DateTime(), nullable=True))
    op.add_column('escalation_states', sa.Column('sla_breach_count', sa.Integer(), nullable=False))
    op.add_column('escalation_states', sa.Column('re_escalation_count', sa.Integer(), nullable=False))
    op.add_column('escalation_states', sa.Column('last_re_escalated_at', sa.DateTime(), nullable=True))
    op.add_column('escalation_states', sa.Column('maintenance_suppressed_until', sa.DateTime(), nullable=True))
    op.add_column('escalation_states', sa.Column('latest_note_at', sa.DateTime(), nullable=True))
    op.add_column('escalation_states', sa.Column('latest_note_by', sa.String(length=255), nullable=True))
    op.add_column('escalation_states', sa.Column('route_snapshot_json', sa.JSON(), nullable=True))
    op.add_column('escalation_states', sa.Column('incident_key', sa.String(length=255), nullable=True))
    op.create_index('idx_esc_aging_status', 'escalation_states', ['aging_bucket', 'current_status'], unique=False)
    op.create_index('idx_esc_re_esc_status', 'escalation_states', ['re_escalation_count', 'current_status'], unique=False)
    op.create_index('idx_esc_sla_status', 'escalation_states', ['sla_breached_at', 'current_status'], unique=False)
    op.create_index(op.f('ix_escalation_states_incident_key'), 'escalation_states', ['incident_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escalation_states_incident_key'), table_name='escalation_states')
    op.drop_index('idx_esc_sla_status', table_name='escalation_states')
    op.drop_index('idx_esc_re_esc_status', table_name='escalation_states')
    op.drop_index('idx_esc_aging_status', table_name='escalation_states')
    op.drop_column('escalation_states', 'incident_key')
    op.drop_column('escalation_states', 'route_snapshot_json')
    op.drop_column('escalation_states', 'latest_note_by')
    op.drop_column('escalation_states', 'latest_note_at')
    op.drop_column('escalation_states', 'maintenance_suppressed_until')
    op.drop_column('escalation_states', 'last_re_escalated_at')
    op.drop_column('escalation_states', 're_escalation_count')
    op.drop_column('escalation_states', 'sla_breach_count')
    op.drop_column('escalation_states', 'sla_breached_at')
    op.drop_column('escalation_states', 'sla_target_seconds')
    op.drop_column('escalation_states', 'aging_bucket')
    op.drop_column('escalation_states', 'aging_seconds')
    op.drop_index('idx_esc_policy_version_enabled', table_name='escalation_policies')
    op.drop_column('escalation_policies', 'route_override_key')
    op.drop_column('escalation_policies', 'bulk_action_enabled')
    op.drop_column('escalation_policies', 'maintenance_window_respected')
    op.drop_column('escalation_policies', 'sla_breach_priority')
    op.drop_column('escalation_policies', 'sla_breach_severity')
    op.drop_column('escalation_policies', 'sla_target_seconds')
    op.drop_column('escalation_policies', 're_escalation_max_count')
    op.drop_column('escalation_policies', 're_escalation_interval_seconds')
    op.drop_column('escalation_policies', 're_escalation_enabled')
    op.drop_column('escalation_policies', 'policy_version')
    op.drop_index('idx_maint_scope', table_name='maintenance_windows')
    op.drop_index('idx_maint_enabled_times', table_name='maintenance_windows')
    op.drop_table('maintenance_windows')
    op.drop_index(op.f('ix_escalation_notes_state_id'), table_name='escalation_notes')
    op.drop_index('idx_esc_note_state_created', table_name='escalation_notes')
    op.drop_table('escalation_notes')
    # ### end Alembic commands ###
