"""Add profitability_scores table

Revision ID: a49ce85f5d0a
Revises: 71b6005b08a0
Create Date: 2026-05-24 11:33:03.277868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a49ce85f5d0a'
down_revision: Union[str, None] = '71b6005b08a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_evaluation_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('search_request_payload_json', sa.JSON(), nullable=False),
    sa.Column('provider_name', sa.String(length=50), nullable=False),
    sa.Column('comparable_listing_ids_json', sa.JSON(), nullable=False),
    sa.Column('excluded_listing_ids_json', sa.JSON(), nullable=False),
    sa.Column('unsafe_reasons_json', sa.JSON(), nullable=False),
    sa.Column('evidence_lines_json', sa.JSON(), nullable=False),
    sa.Column('raw_response_reference', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['canonical_product_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_evaluation_evidences_candidate_id'), 'market_evaluation_evidences', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_market_evaluation_evidences_evidence_id'), 'market_evaluation_evidences', ['evidence_id'], unique=True)
    op.create_table('market_evaluation_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market_evaluation_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('evaluation_status', sa.String(length=50), nullable=False),
    sa.Column('comparable_count', sa.Integer(), nullable=False),
    sa.Column('comparable_quality_score', sa.Float(), nullable=False),
    sa.Column('price_low', sa.Float(), nullable=True),
    sa.Column('price_median', sa.Float(), nullable=True),
    sa.Column('price_high', sa.Float(), nullable=True),
    sa.Column('category_alignment_score', sa.Float(), nullable=False),
    sa.Column('condition_alignment_score', sa.Float(), nullable=False),
    sa.Column('attribute_alignment_score', sa.Float(), nullable=False),
    sa.Column('competition_proxy', sa.String(length=50), nullable=True),
    sa.Column('demand_proxy', sa.String(length=50), nullable=True),
    sa.Column('market_confidence', sa.Float(), nullable=False),
    sa.Column('unsafe_reasons_json', sa.JSON(), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('evidence_summary', sa.Text(), nullable=False),
    sa.Column('search_queries_used_json', sa.JSON(), nullable=False),
    sa.Column('raw_result_count', sa.Integer(), nullable=False),
    sa.Column('filtered_result_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['canonical_product_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_evaluation_results_candidate_id'), 'market_evaluation_results', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_market_evaluation_results_evaluation_status'), 'market_evaluation_results', ['evaluation_status'], unique=False)
    op.create_index(op.f('ix_market_evaluation_results_market_evaluation_id'), 'market_evaluation_results', ['market_evaluation_id'], unique=True)
    op.create_index(op.f('ix_market_evaluation_results_review_required'), 'market_evaluation_results', ['review_required'], unique=False)
    op.create_table('profitability_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profitability_score_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('market_evaluation_id', sa.String(length=255), nullable=True),
    sa.Column('scoring_status', sa.String(length=50), nullable=False),
    sa.Column('decision_status', sa.String(length=50), nullable=False),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('expected_sale_price_low', sa.Float(), nullable=True),
    sa.Column('expected_sale_price_base', sa.Float(), nullable=True),
    sa.Column('expected_sale_price_high', sa.Float(), nullable=True),
    sa.Column('expected_net_profit', sa.Float(), nullable=False),
    sa.Column('expected_margin', sa.Float(), nullable=False),
    sa.Column('expected_roi', sa.Float(), nullable=False),
    sa.Column('confidence_multiplier', sa.Float(), nullable=False),
    sa.Column('confidence_adjusted_profit', sa.Float(), nullable=False),
    sa.Column('profitability_score', sa.Float(), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('unsafe_reasons_json', sa.JSON(), nullable=False),
    sa.Column('explanation_lines_json', sa.JSON(), nullable=False),
    sa.Column('components_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['canonical_product_candidates.candidate_id'], ),
    sa.ForeignKeyConstraint(['market_evaluation_id'], ['market_evaluation_results.market_evaluation_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profitability_scores_candidate_id'), 'profitability_scores', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_profitability_scores_confidence_adjusted_profit'), 'profitability_scores', ['confidence_adjusted_profit'], unique=False)
    op.create_index(op.f('ix_profitability_scores_decision_status'), 'profitability_scores', ['decision_status'], unique=False)
    op.create_index(op.f('ix_profitability_scores_market_evaluation_id'), 'profitability_scores', ['market_evaluation_id'], unique=False)
    op.create_index(op.f('ix_profitability_scores_profitability_score'), 'profitability_scores', ['profitability_score'], unique=False)
    op.create_index(op.f('ix_profitability_scores_profitability_score_id'), 'profitability_scores', ['profitability_score_id'], unique=True)
    op.create_index(op.f('ix_profitability_scores_review_required'), 'profitability_scores', ['review_required'], unique=False)
    op.create_index(op.f('ix_profitability_scores_scoring_status'), 'profitability_scores', ['scoring_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profitability_scores_scoring_status'), table_name='profitability_scores')
    op.drop_index(op.f('ix_profitability_scores_review_required'), table_name='profitability_scores')
    op.drop_index(op.f('ix_profitability_scores_profitability_score_id'), table_name='profitability_scores')
    op.drop_index(op.f('ix_profitability_scores_profitability_score'), table_name='profitability_scores')
    op.drop_index(op.f('ix_profitability_scores_market_evaluation_id'), table_name='profitability_scores')
    op.drop_index(op.f('ix_profitability_scores_decision_status'), table_name='profitability_scores')
    op.drop_index(op.f('ix_profitability_scores_confidence_adjusted_profit'), table_name='profitability_scores')
    op.drop_index(op.f('ix_profitability_scores_candidate_id'), table_name='profitability_scores')
    op.drop_table('profitability_scores')
    op.drop_index(op.f('ix_market_evaluation_results_review_required'), table_name='market_evaluation_results')
    op.drop_index(op.f('ix_market_evaluation_results_market_evaluation_id'), table_name='market_evaluation_results')
    op.drop_index(op.f('ix_market_evaluation_results_evaluation_status'), table_name='market_evaluation_results')
    op.drop_index(op.f('ix_market_evaluation_results_candidate_id'), table_name='market_evaluation_results')
    op.drop_table('market_evaluation_results')
    op.drop_index(op.f('ix_market_evaluation_evidences_evidence_id'), table_name='market_evaluation_evidences')
    op.drop_index(op.f('ix_market_evaluation_evidences_candidate_id'), table_name='market_evaluation_evidences')
    op.drop_table('market_evaluation_evidences')
    # ### end Alembic commands ###
