"""Add Phase A Source Intelligence DB models

Revision ID: a4bae443ecee
Revises: a08ea3afd1a9
Create Date: 2026-05-23 22:10:04.201589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4bae443ecee'
down_revision: Union[str, None] = 'a08ea3afd1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canonical_product_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('canonical_title', sa.Text(), nullable=False),
    sa.Column('canonical_brand', sa.String(length=255), nullable=True),
    sa.Column('canonical_model', sa.String(length=255), nullable=True),
    sa.Column('canonical_mpn', sa.String(length=255), nullable=True),
    sa.Column('canonical_gtins_json', sa.JSON(), nullable=True),
    sa.Column('canonical_condition_family', sa.String(length=50), nullable=True),
    sa.Column('variation_signature', sa.String(length=500), nullable=True),
    sa.Column('bundle_signature', sa.String(length=500), nullable=True),
    sa.Column('source_count', sa.Integer(), nullable=False),
    sa.Column('matched_source_item_ids_json', sa.JSON(), nullable=True),
    sa.Column('match_confidence', sa.Float(), nullable=False),
    sa.Column('ambiguity_flags_json', sa.JSON(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('category_candidates_json', sa.JSON(), nullable=True),
    sa.Column('feature_payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_canonical_brand_model', 'canonical_product_candidates', ['canonical_brand', 'canonical_model'], unique=False)
    op.create_index('idx_canonical_brand_mpn', 'canonical_product_candidates', ['canonical_brand', 'canonical_mpn'], unique=False)
    op.create_index(op.f('ix_canonical_product_candidates_candidate_id'), 'canonical_product_candidates', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_canonical_product_candidates_canonical_brand'), 'canonical_product_candidates', ['canonical_brand'], unique=False)
    op.create_index(op.f('ix_canonical_product_candidates_canonical_model'), 'canonical_product_candidates', ['canonical_model'], unique=False)
    op.create_index(op.f('ix_canonical_product_candidates_canonical_mpn'), 'canonical_product_candidates', ['canonical_mpn'], unique=False)
    op.create_index(op.f('ix_canonical_product_candidates_review_required'), 'canonical_product_candidates', ['review_required'], unique=False)
    op.create_index(op.f('ix_canonical_product_candidates_variation_signature'), 'canonical_product_candidates', ['variation_signature'], unique=False)
    op.create_table('match_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('normalized_item_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=True),
    sa.Column('identifier_hits_json', sa.JSON(), nullable=True),
    sa.Column('title_similarity_score', sa.Float(), nullable=False),
    sa.Column('brand_match_score', sa.Float(), nullable=False),
    sa.Column('model_match_score', sa.Float(), nullable=False),
    sa.Column('mpn_match_score', sa.Float(), nullable=False),
    sa.Column('variation_penalty', sa.Float(), nullable=False),
    sa.Column('bundle_penalty', sa.Float(), nullable=False),
    sa.Column('condition_penalty', sa.Float(), nullable=False),
    sa.Column('ambiguity_flags_json', sa.JSON(), nullable=True),
    sa.Column('explanation_lines_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_evidences_candidate_id'), 'match_evidences', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_match_evidences_evidence_id'), 'match_evidences', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_match_evidences_normalized_item_id'), 'match_evidences', ['normalized_item_id'], unique=False)
    op.create_table('normalized_source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('normalized_item_id', sa.String(length=255), nullable=False),
    sa.Column('source_item_id', sa.String(length=255), nullable=False),
    sa.Column('normalized_title', sa.Text(), nullable=False),
    sa.Column('normalized_brand', sa.String(length=255), nullable=True),
    sa.Column('normalized_model', sa.String(length=255), nullable=True),
    sa.Column('normalized_mpn', sa.String(length=255), nullable=True),
    sa.Column('strict_gtins_json', sa.JSON(), nullable=True),
    sa.Column('loose_gtins_json', sa.JSON(), nullable=True),
    sa.Column('normalized_condition', sa.String(length=50), nullable=True),
    sa.Column('normalized_quantity', sa.Integer(), nullable=True),
    sa.Column('variation_keys_json', sa.JSON(), nullable=True),
    sa.Column('bundle_flags_json', sa.JSON(), nullable=True),
    sa.Column('parsed_attributes_json', sa.JSON(), nullable=True),
    sa.Column('identity_signals_json', sa.JSON(), nullable=True),
    sa.Column('normalization_flags_json', sa.JSON(), nullable=True),
    sa.Column('review_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_normalized_source_items_normalized_brand'), 'normalized_source_items', ['normalized_brand'], unique=False)
    op.create_index(op.f('ix_normalized_source_items_normalized_item_id'), 'normalized_source_items', ['normalized_item_id'], unique=True)
    op.create_index(op.f('ix_normalized_source_items_normalized_model'), 'normalized_source_items', ['normalized_model'], unique=False)
    op.create_index(op.f('ix_normalized_source_items_normalized_mpn'), 'normalized_source_items', ['normalized_mpn'], unique=False)
    op.create_index(op.f('ix_normalized_source_items_review_required'), 'normalized_source_items', ['review_required'], unique=False)
    op.create_index(op.f('ix_normalized_source_items_source_item_id'), 'normalized_source_items', ['source_item_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_source_items_source_item_id'), table_name='normalized_source_items')
    op.drop_index(op.f('ix_normalized_source_items_review_required'), table_name='normalized_source_items')
    op.drop_index(op.f('ix_normalized_source_items_normalized_mpn'), table_name='normalized_source_items')
    op.drop_index(op.f('ix_normalized_source_items_normalized_model'), table_name='normalized_source_items')
    op.drop_index(op.f('ix_normalized_source_items_normalized_item_id'), table_name='normalized_source_items')
    op.drop_index(op.f('ix_normalized_source_items_normalized_brand'), table_name='normalized_source_items')
    op.drop_table('normalized_source_items')
    op.drop_index(op.f('ix_match_evidences_normalized_item_id'), table_name='match_evidences')
    op.drop_index(op.f('ix_match_evidences_evidence_id'), table_name='match_evidences')
    op.drop_index(op.f('ix_match_evidences_candidate_id'), table_name='match_evidences')
    op.drop_table('match_evidences')
    op.drop_index(op.f('ix_canonical_product_candidates_variation_signature'), table_name='canonical_product_candidates')
    op.drop_index(op.f('ix_canonical_product_candidates_review_required'), table_name='canonical_product_candidates')
    op.drop_index(op.f('ix_canonical_product_candidates_canonical_mpn'), table_name='canonical_product_candidates')
    op.drop_index(op.f('ix_canonical_product_candidates_canonical_model'), table_name='canonical_product_candidates')
    op.drop_index(op.f('ix_canonical_product_candidates_canonical_brand'), table_name='canonical_product_candidates')
    op.drop_index(op.f('ix_canonical_product_candidates_candidate_id'), table_name='canonical_product_candidates')
    op.drop_index('idx_canonical_brand_mpn', table_name='canonical_product_candidates')
    op.drop_index('idx_canonical_brand_model', table_name='canonical_product_candidates')
    op.drop_table('canonical_product_candidates')
    # ### end Alembic commands ###
