"""Add execution_attempts table

Revision ID: bb120efa3a17
Revises: 6e7bd6364214
Create Date: 2026-05-24 21:21:51.963846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb120efa3a17'
down_revision: Union[str, None] = '6e7bd6364214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_attempts',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('listing_id', sa.String(), nullable=False),
    sa.Column('candidate_id', sa.String(), nullable=True),
    sa.Column('handoff_id', sa.String(), nullable=True),
    sa.Column('seller_account_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('result_summary', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('failure_boundary', sa.String(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ranking_decision_id', sa.String(), nullable=True),
    sa.Column('scheduler_run_id', sa.String(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index(op.f('ix_execution_attempts_listing_id'), 'execution_attempts', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_attempts_listing_id'), table_name='execution_attempts')
    op.drop_table('execution_attempts')
    # ### end Alembic commands ###
