"""Initial migration

Revision ID: c186701f961f
Revises: 
Create Date: 2026-05-16 10:34:31.485613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c186701f961f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.String(length=255), nullable=False),
    sa.Column('job_name', sa.String(length=255), nullable=False),
    sa.Column('job_scope', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('context_json', sa.JSON(), nullable=True),
    sa.Column('processed_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('excluded_count', sa.Integer(), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('ready_count', sa.Integer(), nullable=False),
    sa.Column('blocked_count', sa.Integer(), nullable=False),
    sa.Column('skipped_count', sa.Integer(), nullable=False),
    sa.Column('retryable_error_count', sa.Integer(), nullable=False),
    sa.Column('review_required_count', sa.Integer(), nullable=False),
    sa.Column('fatal_error_count', sa.Integer(), nullable=False),
    sa.Column('keep_count', sa.Integer(), nullable=False),
    sa.Column('revised_count', sa.Integer(), nullable=False),
    sa.Column('zeroed_count', sa.Integer(), nullable=False),
    sa.Column('withdrawn_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_runs_job_name'), 'job_runs', ['job_name'], unique=False)
    op.create_index(op.f('ix_job_runs_run_id'), 'job_runs', ['run_id'], unique=True)
    op.create_table('source_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_item_id', sa.String(length=255), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_title', sa.String(length=512), nullable=False),
    sa.Column('source_price_jpy', sa.Float(), nullable=False),
    sa.Column('source_shipping_jpy', sa.Float(), nullable=False),
    sa.Column('source_stock_status', sa.String(length=50), nullable=False),
    sa.Column('source_purchase_type', sa.String(length=50), nullable=False),
    sa.Column('image_urls_json', sa.JSON(), nullable=True),
    sa.Column('raw_json', sa.JSON(), nullable=True),
    sa.Column('collected_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_source_platform_url', 'source_items', ['source_platform', 'source_url'], unique=True)
    op.create_index(op.f('ix_source_items_source_item_id'), 'source_items', ['source_item_id'], unique=False)
    op.create_table('product_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('source_item_id', sa.String(length=255), nullable=False),
    sa.Column('source_platform', sa.String(length=50), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=False),
    sa.Column('source_title', sa.String(length=512), nullable=False),
    sa.Column('source_price_jpy', sa.Float(), nullable=False),
    sa.Column('source_shipping_jpy', sa.Float(), nullable=False),
    sa.Column('source_stock_status', sa.String(length=50), nullable=False),
    sa.Column('source_purchase_type', sa.String(length=50), nullable=False),
    sa.Column('image_urls_json', sa.JSON(), nullable=True),
    sa.Column('condition_source', sa.String(length=50), nullable=False),
    sa.Column('pipeline_type', sa.String(length=50), nullable=False),
    sa.Column('decision_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('brand', sa.String(length=255), nullable=True),
    sa.Column('series', sa.String(length=255), nullable=True),
    sa.Column('character', sa.String(length=255), nullable=True),
    sa.Column('product_type', sa.String(length=255), nullable=True),
    sa.Column('ebay_title_candidate', sa.String(length=255), nullable=True),
    sa.Column('ebay_category_id', sa.String(length=50), nullable=True),
    sa.Column('ebay_condition', sa.String(length=50), nullable=True),
    sa.Column('ebay_aspects_json', sa.JSON(), nullable=True),
    sa.Column('missing_required_aspects_json', sa.JSON(), nullable=True),
    sa.Column('listing_readiness_status', sa.String(length=50), nullable=False),
    sa.Column('publish_readiness', sa.Boolean(), nullable=False),
    sa.Column('listing_blockers_json', sa.JSON(), nullable=True),
    sa.Column('inventory_item_draft_json', sa.JSON(), nullable=True),
    sa.Column('offer_draft_json', sa.JSON(), nullable=True),
    sa.Column('expected_sale_price_usd', sa.Float(), nullable=False),
    sa.Column('expected_profit_jpy', sa.Float(), nullable=False),
    sa.Column('expected_profit_rate', sa.Float(), nullable=False),
    sa.Column('standard_score', sa.Float(), nullable=False),
    sa.Column('auto_listable', sa.Boolean(), nullable=False),
    sa.Column('exclude_reason', sa.String(length=255), nullable=True),
    sa.Column('review_reason', sa.String(length=255), nullable=True),
    sa.Column('decision_reason_codes_json', sa.JSON(), nullable=True),
    sa.Column('last_rule_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['source_item_id'], ['source_items.source_item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_candidates_candidate_id'), 'product_candidates', ['candidate_id'], unique=True)
    op.create_index(op.f('ix_product_candidates_listing_readiness_status'), 'product_candidates', ['listing_readiness_status'], unique=False)
    op.create_index(op.f('ix_product_candidates_sku'), 'product_candidates', ['sku'], unique=True)
    op.create_index(op.f('ix_product_candidates_status'), 'product_candidates', ['status'], unique=False)
    op.create_table('candidate_evidences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_payload_json', sa.JSON(), nullable=False),
    sa.Column('rule_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['product_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidate_evidences_candidate_id'), 'candidate_evidences', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_candidate_evidences_evidence_id'), 'candidate_evidences', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_candidate_evidences_evidence_type'), 'candidate_evidences', ['evidence_type'], unique=False)
    op.create_table('ebay_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('marketplace_id', sa.String(length=50), nullable=False),
    sa.Column('inventory_item_status', sa.String(length=50), nullable=False),
    sa.Column('offer_id', sa.String(length=255), nullable=True),
    sa.Column('offer_status', sa.String(length=50), nullable=False),
    sa.Column('listing_id', sa.String(length=255), nullable=True),
    sa.Column('listing_price_usd', sa.Float(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('merchant_location_key', sa.String(length=255), nullable=True),
    sa.Column('fulfillment_policy_id', sa.String(length=255), nullable=True),
    sa.Column('payment_policy_id', sa.String(length=255), nullable=True),
    sa.Column('return_policy_id', sa.String(length=255), nullable=True),
    sa.Column('last_publish_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('last_publish_error', sa.Text(), nullable=True),
    sa.Column('last_revise_error', sa.Text(), nullable=True),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['product_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ebay_listings_listing_id'), 'ebay_listings', ['listing_id'], unique=True)
    op.create_index(op.f('ix_ebay_listings_offer_id'), 'ebay_listings', ['offer_id'], unique=True)
    op.create_index(op.f('ix_ebay_listings_sku'), 'ebay_listings', ['sku'], unique=True)
    op.create_table('monitoring_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('sku', sa.String(length=255), nullable=False),
    sa.Column('event_scope', sa.String(length=50), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('before_value', sa.Text(), nullable=True),
    sa.Column('after_value', sa.Text(), nullable=True),
    sa.Column('action_taken', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['product_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monitoring_events_event_id'), 'monitoring_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_monitoring_events_sku'), 'monitoring_events', ['sku'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_monitoring_events_sku'), table_name='monitoring_events')
    op.drop_index(op.f('ix_monitoring_events_event_id'), table_name='monitoring_events')
    op.drop_table('monitoring_events')
    op.drop_index(op.f('ix_ebay_listings_sku'), table_name='ebay_listings')
    op.drop_index(op.f('ix_ebay_listings_offer_id'), table_name='ebay_listings')
    op.drop_index(op.f('ix_ebay_listings_listing_id'), table_name='ebay_listings')
    op.drop_table('ebay_listings')
    op.drop_index(op.f('ix_candidate_evidences_evidence_type'), table_name='candidate_evidences')
    op.drop_index(op.f('ix_candidate_evidences_evidence_id'), table_name='candidate_evidences')
    op.drop_index(op.f('ix_candidate_evidences_candidate_id'), table_name='candidate_evidences')
    op.drop_table('candidate_evidences')
    op.drop_index(op.f('ix_product_candidates_status'), table_name='product_candidates')
    op.drop_index(op.f('ix_product_candidates_sku'), table_name='product_candidates')
    op.drop_index(op.f('ix_product_candidates_listing_readiness_status'), table_name='product_candidates')
    op.drop_index(op.f('ix_product_candidates_candidate_id'), table_name='product_candidates')
    op.drop_table('product_candidates')
    op.drop_index(op.f('ix_source_items_source_item_id'), table_name='source_items')
    op.drop_index('idx_source_platform_url', table_name='source_items')
    op.drop_table('source_items')
    op.drop_index(op.f('ix_job_runs_run_id'), table_name='job_runs')
    op.drop_index(op.f('ix_job_runs_job_name'), table_name='job_runs')
    op.drop_table('job_runs')
    # ### end Alembic commands ###
