"""Add execution_history table

Revision ID: d9fb6dac0982
Revises: bb120efa3a17
Create Date: 2026-05-25 18:09:33.780512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9fb6dac0982'
down_revision: Union[str, None] = 'bb120efa3a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('execution_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('attempt_id', sa.String(length=255), nullable=False),
    sa.Column('listing_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('dry_run', sa.Boolean(), nullable=False),
    sa.Column('from_state', sa.String(length=50), nullable=True),
    sa.Column('to_state', sa.String(length=50), nullable=True),
    sa.Column('error_code', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['execution_attempts.attempt_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_history_attempt_id'), 'execution_history', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_execution_history_created_at'), 'execution_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_history_event_type'), 'execution_history', ['event_type'], unique=False)
    op.create_index(op.f('ix_execution_history_listing_id'), 'execution_history', ['listing_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_execution_history_listing_id'), table_name='execution_history')
    op.drop_index(op.f('ix_execution_history_event_type'), table_name='execution_history')
    op.drop_index(op.f('ix_execution_history_created_at'), table_name='execution_history')
    op.drop_index(op.f('ix_execution_history_attempt_id'), table_name='execution_history')
    op.drop_table('execution_history')
    # ### end Alembic commands ###
