"""Add listing_decisions table

Revision ID: ea36a232da27
Revises: a49ce85f5d0a
Create Date: 2026-05-24 14:36:48.042627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea36a232da27'
down_revision: Union[str, None] = 'a49ce85f5d0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ranking_decision_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.String(length=255), nullable=False),
    sa.Column('seller_account_id', sa.String(length=255), nullable=False),
    sa.Column('environment', sa.String(length=50), nullable=False),
    sa.Column('ranking_score', sa.Float(), nullable=False),
    sa.Column('decision_class', sa.String(length=50), nullable=False),
    sa.Column('decision_reason', sa.Text(), nullable=False),
    sa.Column('queue_type', sa.String(length=50), nullable=False),
    sa.Column('queue_rank', sa.Integer(), nullable=False),
    sa.Column('launch_priority_bucket', sa.String(length=50), nullable=True),
    sa.Column('review_priority_bucket', sa.String(length=50), nullable=True),
    sa.Column('execution_blocked', sa.Boolean(), nullable=False),
    sa.Column('block_reasons_json', sa.JSON(), nullable=False),
    sa.Column('recheck_required', sa.Boolean(), nullable=False),
    sa.Column('stale_flag', sa.Boolean(), nullable=False),
    sa.Column('explanation_lines_json', sa.JSON(), nullable=False),
    sa.Column('ranking_components_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['canonical_product_candidates.candidate_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_listing_decisions_candidate_id'), 'listing_decisions', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_listing_decisions_decision_class'), 'listing_decisions', ['decision_class'], unique=False)
    op.create_index(op.f('ix_listing_decisions_launch_priority_bucket'), 'listing_decisions', ['launch_priority_bucket'], unique=False)
    op.create_index(op.f('ix_listing_decisions_queue_rank'), 'listing_decisions', ['queue_rank'], unique=False)
    op.create_index(op.f('ix_listing_decisions_queue_type'), 'listing_decisions', ['queue_type'], unique=False)
    op.create_index(op.f('ix_listing_decisions_ranking_decision_id'), 'listing_decisions', ['ranking_decision_id'], unique=True)
    op.create_index(op.f('ix_listing_decisions_ranking_score'), 'listing_decisions', ['ranking_score'], unique=False)
    op.create_index(op.f('ix_listing_decisions_review_priority_bucket'), 'listing_decisions', ['review_priority_bucket'], unique=False)
    op.create_index(op.f('ix_listing_decisions_seller_account_id'), 'listing_decisions', ['seller_account_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_listing_decisions_seller_account_id'), table_name='listing_decisions')
    op.drop_index(op.f('ix_listing_decisions_review_priority_bucket'), table_name='listing_decisions')
    op.drop_index(op.f('ix_listing_decisions_ranking_score'), table_name='listing_decisions')
    op.drop_index(op.f('ix_listing_decisions_ranking_decision_id'), table_name='listing_decisions')
    op.drop_index(op.f('ix_listing_decisions_queue_type'), table_name='listing_decisions')
    op.drop_index(op.f('ix_listing_decisions_queue_rank'), table_name='listing_decisions')
    op.drop_index(op.f('ix_listing_decisions_launch_priority_bucket'), table_name='listing_decisions')
    op.drop_index(op.f('ix_listing_decisions_decision_class'), table_name='listing_decisions')
    op.drop_index(op.f('ix_listing_decisions_candidate_id'), table_name='listing_decisions')
    op.drop_table('listing_decisions')
    # ### end Alembic commands ###
